---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ dockerhub_registry_username }}"
        password: "{{ dockerhub_registry_password }}"

    - name: Build and push the Docker image to Docker Hub
      docker_image:
        build:
          path: "./"
        name: "{{ dockerhub_registry_username }}/my-country-service"
        tag: "{{ image_tag }}"
        source: build
        push: yes
        state: present

    - name: Pull Docker image (optional, for verification or on target nodes)
      docker_image:
        name: "{{ dockerhub_registry_username }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: "deployment.yaml"
        kubeconfig: "config"

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: "service.yaml"
        kubeconfig: "config"
